import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Saira } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./lib/ThemeProvider";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const siara = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${siara.variable} ${inter.variable}  antialiased`}
      >
        <Providers >
          <div className="bg-white  dark:bg-[#101428]">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
